name: Build and test Logfile::Tail

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '12 5 2,16 * *'

jobs:
  build:
    name: Run tests in container
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: [ fedora-latest, centos-8, centos-7 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set the right OS in the Dockerfile
        run: sed "s#^FROM.*#FROM $( echo ${{ matrix.os }} | sed 's#^fedora-#registry.fedoraproject.org/fedora:#; s#^centos-#registry.centos.org/centos:#;' )#" ci/Dockerfile
      - name: Build image
        run: docker build -t logfile-tail -f ci/Dockerfile .
      - name: Run the tests with installed module
        run: docker run -e LOGFILE_TAIL_SCRIPT=/usr/bin/logfile-tail --rm logfile-tail t/test.sh
